IRIS_PLATFORM_VERSION = 12.1

IRIS_BUILD_DATE := $(shell date -u +%Y%m%d-%H%M)

IRIS_BUILDTYPE ?= UNOFFICIAL

IRIS_VERSION_SUFFIX := $(IRIS_BUILD_DATE)-$(IRIS_BUILDTYPE)$(IRIS_EXTRAVERSION)

# Internal version
IRIS_VERSION := $(IRIS_PLATFORM_VERSION)-$(IRIS_VERSION_SUFFIX)-$(IRIS_BUILD)

# Display version
IRIS_DISPLAY_VERSION := $(IRIS_PLATFORM_VERSION)-$(IRIS_VERSION_SUFFIX)
